# Generated by Django 6.0.4 on 2026-05-01 14:15

import django.db.models.deletion
from django.db import migrations, models

def create_initial_job_statuses(apps, schema_editor):
    JobStatus = apps.get_model("commissions", "JobStatus")

    JobStatus.objects.create(name="OPEN", order=1)
    JobStatus.objects.create(name="FULL", order=2)
    JobStatus.objects.create(name="COMPLETED", order=3)
    JobStatus.objects.create(name="DISCONTINUED", order=4)

def create_initial_application_statuses(apps, schema_editor):
    ApplicationStatus = apps.get_model("commissions", "ApplicationStatus")

    ApplicationStatus.objects.create(name="PENDING", order=1)
    ApplicationStatus.objects.create(name="ACCEPTED", order=2)
    ApplicationStatus.objects.create(name="REJECTED", order=3)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_role_profile_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CommissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('people_required', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('commission_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commissions.commissiontype')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commissions.jobstatus')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.RunPython(create_initial_job_statuses),
        migrations.RunPython(create_initial_application_statuses),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('manpower_required', models.PositiveIntegerField()),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='commissions.commission')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commissions.jobstatus')),
            ],
            options={
                'ordering': ['-status', '-manpower_required', 'role'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='accounts.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='commissions.job')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_applications', to='commissions.applicationstatus')),
            ],
            options={
                'ordering': ['status', '-applied_on'],
            },
        ),
    ]
