# Generated by Django 6.0.4 on 2026-05-06 15:18
from django.db import migrations

def create_job_statuses(apps, schema_editor):
    JobStatus = apps.get_model('commissions', 'JobStatus')

    statuses = [
        ("OPEN", 1),
        ("FULL", 2),
        ("COMPLETED", 3),
        ("DISCONTINUED", 4),
    ]

    for name, order in statuses:
        JobStatus.objects.update_or_create(
            name=name,
            defaults={"order": order}
        )

def delete_job_statuses(apps, schema_editor):
    JobStatus = apps.get_model('commissions', 'JobStatus')
    JobStatus.objects.filter(
        name__in=["OPEN", "FULL", "COMPLETED", "DISCONTINUED"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_job_statuses, delete_job_statuses),
    ]

