# Generated by Django 6.0.4 on 2026-04-30 20:38

import commissions.models
import django.db.models.deletion
from django.db import migrations, models

def create_initial_job_statuses(apps, schema_editor):
    JobStatus = apps.get_model("commissions", "JobStatus")

    JobStatus.objects.create(name="OPEN", order=1)
    JobStatus.objects.create(name="FULL", order=2)

def create_initial_application_statuses(apps, schema_editor):
    JobStatus = apps.get_model("commissions", "JobStatus")

    JobStatus.objects.create(name="PENDING", order=1)
    JobStatus.objects.create(name="ACCEPTED", order=2)
    JobStatus.objects.create(name="REJECTED", order=3)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_profile_roles'),
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RunPython(create_initial_job_statuses),
        migrations.RunPython(create_initial_application_statuses),
        migrations.AddField(
            model_name='commission',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='people_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('manpower_required', models.PositiveIntegerField()),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='commissions.commission')),
                ('status', models.ForeignKey(default=commissions.models.get_default_job_status, on_delete=django.db.models.deletion.PROTECT, to='commissions.jobstatus')),
            ],
            options={
                'ordering': ['-status', '-manpower_required', 'role'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='accounts.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='commissions.job')),
                ('status', models.ForeignKey(default=commissions.models.get_default_job_status, on_delete=django.db.models.deletion.PROTECT, related_name='job_applications', to='commissions.applicationstatus')),
            ],
            options={
                'ordering': ['status', '-applied_on'],
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.ForeignKey(default=commissions.models.get_default_job_status, on_delete=django.db.models.deletion.PROTECT, to='commissions.jobstatus'),
        ),
    ]
