# Generated by Django 6.0.4 on 2026-05-06 15:31

from django.db import migrations
statuses = ["Art", "Programming", "Writing", "Video Editing"]
def create_commission_types(apps, schema_editor):
    CommissionType = apps.get_model('commissions', 'CommissionType')

    for name in statuses:
        CommissionType.objects.update_or_create(
            name=name,
        )

def delete_commission_types(apps, schema_editor):
    CommissionType = apps.get_model('commissions', 'CommissionType')
    CommissionType.objects.filter(
        name__in=statuses
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_auto_20260506_2322'),
    ]

    operations = [
        migrations.RunPython(create_commission_types, delete_commission_types),
    ]
