# Generated by Django 5.2.12 on 2026-03-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='steps',
            field=models.TextField(blank=True),
        ),
    ]
