# Generated by Django 6.0.4 on 2026-04-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0002_project_description_project_materials_project_steps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['-name']},
        ),
    ]
